/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportform;

import indohotel.utility.Koneksi;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author risqu
 */
public class RoomReport extends javax.swing.JInternalFrame {

    Koneksi conn = new Koneksi();
    String query1 = "SELECT jeniskamar.nama_jenis_kamar, COUNT(roomcheckout.id_kamar) FROM roomcheckout, kamar, jeniskamar WHERE kamar.id_kamar = roomcheckout.id_kamar AND kamar.id_jenis_kamar = jeniskamar.id_jenis_kamar GROUP BY jeniskamar.id_jenis_kamar";
    String query2 = "SELECT roomcheckout.tgl_checkout, COUNT(roomcheckout.id_checkout) FROM `roomcheckout` GROUP BY MONTH(tgl_checkout)";
    
    public RoomReport() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI uI = (BasicInternalFrameUI) this.getUI();
        uI.setNorthPane(null);
        
        this.setPreferredSize(new Dimension(506, 395));
        setSize(new Dimension(506, 395));
        
        
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(conn.getKoneksi());
            dataset.executeQuery(query1);
            JFreeChart chart = ChartFactory.createBarChart("Report Room Type Usage", null, null, dataset);
            ChartPanel cp = new ChartPanel(chart);
            cp.setPreferredSize(new Dimension(220, 147));
            cp.setSize(new Dimension(220, 147));
            jPanel2.add(cp, BorderLayout.CENTER);
            jPanel2.validate();
        } catch (SQLException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.toString());
        }
        
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(conn.getKoneksi());
            dataset.executeQuery(query2);
            JFreeChart chart = ChartFactory.createBarChart("Report Room Usage", null, null, dataset);
            ChartPanel cp = new ChartPanel(chart);
            cp.setPreferredSize(new Dimension(220, 147));
            cp.setSize(new Dimension(220, 147));
            jPanel3.add(cp, BorderLayout.CENTER);
            jPanel3.validate();
        } catch (SQLException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.toString());
        }
        
        try {
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(conn.getKoneksi());
            dataset.executeQuery("SELECT jeniskamar.nama_jenis_kamar, SUM(pembayaran.total_pembayaran) FROM pembayaran, roomcheckout, kamar, jeniskamar WHERE pembayaran.id_checkout = roomcheckout.id_checkout AND roomcheckout.id_kamar = kamar.id_kamar AND kamar.id_jenis_kamar = jeniskamar.id_jenis_kamar GROUP BY kamar.id_jenis_kamar");
            JFreeChart chart = ChartFactory.createBarChart("Report Revenue", null, null, dataset);
            ChartPanel cp = new ChartPanel(chart);
            cp.setPreferredSize(new Dimension(220, 147));
            cp.setSize(new Dimension(220, 240));
            jPanel4.add(cp, BorderLayout.CENTER);
            jPanel4.validate();
        } catch (SQLException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_report2 = new javax.swing.JButton();
        btn_report3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jButton1.setText("Summary Report");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_report2.setText("Room Report");
        btn_report2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_report2MousePressed(evt);
            }
        });

        btn_report3.setText("Report Employee");
        btn_report3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_report3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_report3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_report2))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_report2)
                            .addComponent(btn_report3))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report1.jasper"), null, conn.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void btn_report2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_report2MousePressed
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportRoomAvailable.jasper"), null, conn.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_report2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_report3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_report3MousePressed
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportEmployee.jasper"), null, conn.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(RoomReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_report3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_report2;
    private javax.swing.JButton btn_report3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
